apiVersion: v1
kind: Service
metadata:
  name: webapp-census-service
spec:
  type: LoadBalancer # O puedes usar ClusterIP si no necesitas exponerlo fuera del cluster
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: webapp-census
